export let products = [
  {
    id: 1,
    tittle: "BELCANDO CORDERO Y PATATAS CON ARANDANO ",
    price: 2990,
    stock: 10,
    description: "Deliciosa comida sabor a cordero y patatas 125g",
    category: "alimento",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451216/CORDERO-Y-PATATAS-CON-ARANDANO_xlee2p.jpg",
  },
  {
    id: 2,
    tittle: "BELCANDO JUNIOR AVE Y HUEVO",
    price: 4990,
    stock: 14,
    category: "alimento",
    description: "Deliciosa comida sabor a Ave y Huevo",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451252/JUNIOR-AVE-Y-HUEVO_hl9hek.jpg",
  },
  {
    id: 3,
    tittle: "ADAPTIL COLLAR PERROS M-L",
    price: 16990,
    stock: 20,
    category: "salud",
    description: "Super collar para tu mascota reductor de stress ",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451474/collar-adaptil-grande_m8jfck.jpg",
  },
  {
    id: 4,
    tittle: "AFP SPARKLE CEPILLO DEDO/PASTA",
    price: 13000,
    stock: 18,
    category: "salud",
    description: "Cepillo para dentadura canina",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451558/800x800_sparkle_xpulwq.jpg",
  },
  {
    id: 5,
    tittle: "ARNES REFLECTANTE",
    price: 9900,
    stock: 11,
    category: "correa y collares",
    description: "Arnes top reflectante canino",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451631/15728539_1395539790476896_3985217059226124288_n_mw7cjl.jpg",
  },
  {
    id: 6,
    tittle: "CLUB P&G CORREA DE ENTRENAMIENTO ROJA – S",
    price: 3390,
    stock: 5,
    category: "correa y collares",
    description: "Correo de entranmiento Canino",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451702/short-dog-leash-6-scaled_wongqf.jpg",
  },
  {
    id: 7,
    tittle: "CLUB COMEDERO LICK MAT ",
    price: 4200,
    stock: 14,
    category: "juguete",
    description: "Clib comedero LIck Mat de silicona ",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451781/COMEDERO-DE-SILICONA-PARA-LAMER-PEZ_cvbgq1.webp",
  },
  {
    id: 8,
    tittle: "NINA OTTOSSON CAT PUZZLE BUGGIN OUT NIVEL 2",
    price: 22000,
    stock: 8,
    category: "juguete",
    description: "Puzzle felino para entrentener a tu gatito",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1687451849/175398815-origpic-cd81d7_uuj2yz.jpg",
  },
  {
    id: 9,
    tittle: "ACANA FREE-RUN POULTRY DOG ",
    price: 18490,
    stock: 26,
    description:
      "Pollo de corral pavo y huevos del nido son entregados frescos de las granjas locales en proporciones de presa entera. ",
    category: "alimento",
    img: "https://res.cloudinary.com/drids8rm1/image/upload/v1688407124/free-run-poultry_bmkbxw.jpg",
  },
];
